# Site settings
title: Run Program
header-img: img/home-bg.png
email: dearmandenise@gmail.com
copyright_name: denisedearman
description: > # this means to ignore newlines until "baseurl:"
  It's a marathon not a sprint
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  denisedearman
learn_profile: denisedearman
email_username: dearmandenise@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
